export interface AffirmationCategory {
  id: string;
  label: string;
  shortLabel: string;
  focus: string;
  affirmations: string[];
}

export const AFFIRMATION_CATEGORIES: AffirmationCategory[] = [
  {
    id: "panic",
    label: "Panic & Acute Anxiety",
    shortLabel: "Panic",
    focus: "Grounding, safety, and physical reassurance",
    affirmations: [
      "This feeling is intense, but it is temporary; it will pass.",
      "I am safe in this very moment, right where I am.",
      "My body is experiencing a false alarm; I am not in actual danger.",
      "I can step back and let my nervous system slow down at its own pace.",
      "Inhale, exhale. I am bringing my focus back to my breath.",
      "This wave will peak, and then it will recede. I just have to ride it out.",
      "I don't need to fight this feeling; I can let it flow through me and leave.",
      "My heart is beating fast to protect me, but I am safe to slow down now.",
      "I am anchored, I am grounded, and I am OK.",
      "I have survived every panic attack I've ever had. I will get through this one too.",
    ],
  },
  {
    id: "anxiety",
    label: "General Anxiety & Overwhelm",
    shortLabel: "Anxiety",
    focus: "Releasing control, pacing, and quiet confidence",
    affirmations: [
      "I do not have to figure everything out right this second.",
      "I am allowed to take things one small step at a time.",
      "Thoughts are just thoughts; they are not absolute facts or predictions.",
      "I am letting go of the things I cannot control and focusing on what I can.",
      "It is completely safe for me to slow down my thoughts and breathe.",
      "I have handled difficult things before, and I can handle whatever comes next.",
      "I am choosing to be kind to myself while I navigate this uncertainty.",
      "I don't have to be perfect to be secure.",
      "I can sit with this discomfort without letting it dictate my day.",
      "My peace is worth protecting; I can say no to things that drain me.",
    ],
  },
  {
    id: "depression",
    label: "Depression & Low-Energy Days",
    shortLabel: "Depression",
    focus: "Self-compassion, low expectations, and gentle hope",
    affirmations: [
      "My worth is not defined by my productivity or my mood today.",
      "I am doing the best I can with the energy I have right now, and that is enough.",
      "I give myself permission to rest without feeling guilty.",
      "This heavy cloud is a passing state of mind, not a permanent reality.",
      "Even the smallest step forward—just getting out of bed or drinking water—is a win.",
      "I am allowed to feel sad or empty without judging myself for it.",
      "My current feelings do not rewrite my entire future.",
      "I will treat myself with the same gentleness I would offer a friend who is hurting.",
      "I don't have to force a smile; I can just exist as I am today.",
      "There will be brighter, lighter days ahead, even if I can't see them right now.",
    ],
  },
  {
    id: "parents",
    label: "Parents",
    shortLabel: "Parents",
    focus: "Grace, letting go of perfection, and recognizing effort",
    affirmations: [
      "There is no such thing as a perfect parent; I am a good and loving parent.",
      "I am exactly the parent my children need, flaws and all.",
      "A difficult moment or a bad day does not erase all the love I give.",
      "I am allowed to feel tired, frustrated, or overwhelmed; parenting is hard work.",
      "Taking care of my own needs is a vital part of taking care of my family.",
      "I can apologize to my kids when I make a mistake, and we can grow together.",
      "I am teaching my children how to navigate real emotions by being honest with mine.",
      "I don't have to do it all perfectly to do it well.",
      "I am creating a safe, loving environment, and that is what matters most.",
      "Tomorrow is a fresh start for both me and my kids.",
    ],
  },
  {
    id: "caregivers",
    label: "Caregivers",
    shortLabel: "Caregivers",
    focus: "Boundaries, recognizing self-worth, and preventing burnout",
    affirmations: [
      "I am doing incredibly important, deeply meaningful work.",
      "My needs matter just as much as the needs of the person I am caring for.",
      "I cannot pour from an empty cup; choosing rest is an act of necessity, not selfishness.",
      "I am allowed to set boundaries to protect my own physical and emotional health.",
      "I cannot control every outcome, but I can control how gently I treat myself.",
      "It is completely okay to feel frustrated, grief-stricken, or exhausted sometimes.",
      "I am allowed to ask for help, and accepting support is a sign of strength.",
      "I am doing enough, I have given enough, and I am enough.",
      "I will honor the limits of my time, my energy, and my emotional capacity.",
      "I matter independent of what I do for others.",
    ],
  },
  {
    id: "burnout",
    label: "Professional Burnout",
    shortLabel: "Burnout",
    focus: "Separation of identity from work, setting limits, and mental detachment",
    affirmations: [
      "My job is what I do, not who I am.",
      "I am allowed to close my laptop, shut off my notifications, and step away.",
      "The world will not fall apart if I take a break or leave a task for tomorrow.",
      "I do not have to carry the weight of every problem myself.",
      "I am allowed to work at a sustainable pace rather than an exhausting one.",
      "I can say no to extra tasks without feeling like a failure.",
      "I deserve a life that is full, restful, and entirely separate from my career.",
      "My boundaries are necessary for my long-term well-being and success.",
      "I am choosing to prioritize my health over a never-ending to-do list.",
      "I can care about my responsibilities without letting them consume my peace.",
    ],
  },
  {
    id: "grief",
    label: "Grief & Loss",
    shortLabel: "Grief",
    focus: "Honoring the pain, releasing timelines, and gentle survival",
    affirmations: [
      "There is no right or wrong way to grieve; I am allowed to feel whatever comes up.",
      "I will be gentle with myself as I navigate this heavy space.",
      "My grief is a reflection of deep love, and I will honor it at my own pace.",
      "I don't have to carry this sadness perfectly; I just have to breathe through it.",
      "It is okay to have good moments and hard moments all in the same day.",
      "I give myself permission to feel the pain, and permission to seek rest from it.",
      "Love persists beyond absence, and those memories belong to me forever.",
      "I am allowed to miss what was, while gently existing in what is.",
      "Healing isn't forgetting; it is learning to carry the story with grace.",
      "One breath, one step, one moment at a time is all that is required of me today.",
    ],
  },
  {
    id: "perfectionism",
    label: "Perfectionism & Imposter Syndrome",
    shortLabel: "Perfectionism",
    focus: "Embracing mistakes, decoupling worth from achievement, and self-acceptance",
    affirmations: [
      "My worth is inherent; it is not earned through constant doing or achieving.",
      "I belong in the rooms I am in, and I have earned my place at the table.",
      "I am allowed to be a masterpiece and a work in progress at the same time.",
      "Mistakes are not a sign of failure; they are simply proof that I am growing.",
      "I do not need to be flawless to be valued, respected, or capable.",
      "I release the impossible standard of perfection and choose the peace of \"good enough.\"",
      "I am doing the best I can with what I know right now, and that is completely sufficient.",
      "I don't have to know everything to be incredibly good at what I do.",
      "I am choosing to focus on my progress rather than my perceived shortcomings.",
      "I am exactly where I need to be, and I am entirely capable of handling the next step.",
    ],
  },
  {
    id: "chronic-pain",
    label: "Chronic Illness & Physical Pain",
    shortLabel: "Chronic Pain",
    focus: "Reconciling with the body, managing frustration, and finding peace within limitations",
    affirmations: [
      "My body is doing the best it can to care for me today, and I am grateful for its effort.",
      "I am more than my physical limitations or the pain I am experiencing.",
      "On low-energy days, resting is the most productive thing I can do.",
      "I do not have to fight my body; I can partner with it to find comfort.",
      "My value as a person does not depend on my physical stamina or productivity.",
      "I give myself permission to grieve the things I cannot do today.",
      "I will listen to my body's cues and honor its need for quiet and rest.",
      "This flare-up or pain is a state I am passing through, not my permanent destination.",
      "I can find moments of peace and quiet joy even within physical discomfort.",
      "I am gentle with my mind when my body is carrying a heavy load.",
    ],
  },
  {
    id: "boundaries",
    label: "Setting Boundaries",
    shortLabel: "Boundaries",
    focus: "Overcoming guilt, protecting personal peace, and standing firm",
    affirmations: [
      "Saying \"no\" to others is a vital way of saying \"yes\" to my own well-being.",
      "I am responsible for communicating my limits, not for managing other people's reactions.",
      "My peace of mind is worth protecting, even if it makes others uncomfortable.",
      "I do not need to over-explain or justify my boundaries; \"no\" is a complete sentence.",
      "Choosing myself is an act of survival, not an act of selfishness.",
      "I am letting go of the need to fix or manage situations that do not belong to me.",
      "Real love and respect will always leave room for my personal boundaries.",
      "I can be a kind, supportive person while still holding a firm line for my health.",
      "I release the weight of trying to keep everyone around me happy at my own expense.",
      "I am worthy of the same time, care, and space that I so freely give to others.",
    ],
  },
  {
    id: "transitions",
    label: "Life Transitions & Uncertainty",
    shortLabel: "Transitions",
    focus: "Sitting with the unknown, trusting adaptability, and letting go of the final plan",
    affirmations: [
      "I do not need to see the entire path ahead to take the next faithful step.",
      "Change is uncomfortable, but it is also the place where new growth begins.",
      "I trust my ability to adapt, learn, and find my footing in unfamiliar territory.",
      "It is okay to feel unsteady right now; transitions take time to sort out.",
      "I am letting go of how I thought things would go and accepting things as they are.",
      "The unknown holds beautiful possibilities alongside the uncertainty.",
      "I have survived big changes before, and I have the tools to handle this one too.",
      "I give myself grace while I am in this \"in-between\" chapter of my life.",
      "I don't need to have a perfect plan; I just need to stay anchored in the present.",
      "I am safe right here in the transition, moving at a pace that works for me.",
    ],
  },
];
